### ISSUE TITLE
Chapter 7 - Code references unknown member

### ISSUE THREAD

**Issue by JPMoresmau** [thebracket/rustrogueliketutorial#28]
In chapter 7, (Dealing damage) you introduce clear_content_index as a function using the tile_content member way before it's added to the struct. At this point in the code, if I test, there is a bug that the player can move over a monster, because both think the cell is free and move into the same one. I think that's because the various systems run concurrently, but I don't know how to implement the dependencies you mention in the text.

**Comment by Zireael07** [comment]
Ninja'd! I was going to report both problems.
The latter problem would be easily fixed by expanding the turn system first and doing the rest of the combat system second...
In addition, chapter 1.5 doesn't make it explicit that you have to give a name to the player, if you didn't do it, combat doesn't work (I just spent half an hour wondering why it wasn't doing jack)
