### ISSUE TITLE
Targeting in chapter 3.19 has a BIG problem at higher player x,y coords

### ISSUE THREAD

**Issue by Zireael07** [thebracket/rustrogueliketutorial#32]
(It is possible to trigger a problem within standard 80,50 map bounds, so it's not a case of people wanting really big maps. It seems to happen at roughly y = 40ish and x = 35ish.
I removed the range check on targeting (just to see if it was the culprit), so ALL tiles in view should be highlighted blue (=available for targeting). I used the right-hand panel to print out some stuff for debugging (player position is labeled as such, X and Y are the camera min and max bounds for the relevant coordinate, and they all look to be correct)

Some screenshots to illustrate:
![Screenshot 2019-11-15 14:00:09](https://user-images.githubusercontent.com/4525388/68945538-e83a6100-07b0-11ea-903d-03610eafe776.png)

![Screenshot 2019-11-15 13:59:39](https://user-images.githubusercontent.com/4525388/68945555-f25c5f80-07b0-11ea-84d5-a1325576c169.png)
Note the tiles above the player aren't lit anymore.

![Screenshot 2019-11-15 13:58:50](https://user-images.githubusercontent.com/4525388/68945584-02743f00-07b1-11ea-9f0a-6e7d6b7c8ed1.png)
Even more tiles in view aren't lit.

![Screenshot 2019-11-15 13:58:13](https://user-images.githubusercontent.com/4525388/68945608-0c963d80-07b1-11ea-9e4b-673887ef202b.png)
Past a certain point, no tiles are lit and therefore your grenade/fireball scroll is useless.

Everything points to
 ` let screen_x = idx.x - min_x;
                let screen_y = idx.y - min_y;
                if screen_x > min_x && screen_x < max_x && screen_y > min_y && screen_y < max_y ` part of the targeting code being the culprit. 

Unfortunately I haven't figured out a solution yet. I would probably try cribbing from `camera.rs`, doing `for ty in min_y .. max_y { for tx in min_x .. max_x` kinda thing?

**Comment by thebracket** [comment]
I'm having a hard time reproducing this. Working from the source in `chapter-41-camera`:

* I commented out the spawn section starting at line 103 of `spawner.rs`, and just spawn `fireball_scroll(ecs, x, y)`.
* I added player position printing to `draw_ui` in `gui.rs`.

Then I roam around blasting on the default `80x50` map and targeting seems to be working?

![targeting-bug](https://user-images.githubusercontent.com/14896751/68949753-60d4f980-0780-11ea-8701-4d6da9e29884.gif)

I'll try again in WASM, in case it's related to that - but I'm obviously missing something?

**Comment by Zireael07** [comment]
Hmm, my code is here: https://github.com/Zireael07/rust-web-roguelike-reboot, but I have looked that over many times and I can't spot a difference to the tutorial code... Maybe a second pair of eyes will help?

**Comment by thebracket** [comment]
Aha. I set my map to 256x256 and went down to the 7,239 region and I can replicate it. I'll see what I can do.

**Comment by thebracket** [comment]
Entertainingly, if you comment out the entire bounds check:

```rust
//if screen_x > min_x && screen_x < max_x && screen_y > min_y && screen_y < max_y {
                    ctx.set_bg(screen_x, screen_y, RGB::named(rltk::BLUE));
                    available_cells.push(idx);
                //}
```

It actually works (since the viewshed can never expand beyond the map boundaries after a recent fix). It'll crash if you extend view radius beyond the visible map, though (which would be kinda pointless).

Throw in some debug printing: `println!("Screen: {}, {}, Min/Max: {}..{} / {}..{}", screen_x, screen_y, min_x, max_x, min_y, max_y);` and you can see why this is happening. So a quick run with that showed the following:

```
Screen: 38, 25, Min/Max: 173..253 / 12..62
Screen: 37, 25, Min/Max: 173..253 / 12..62
Screen: 36, 25, Min/Max: 173..253 / 12..62
Screen: 35, 25, Min/Max: 173..253 / 12..62
Screen: 40, 25, Min/Max: 173..253 / 12..62
```

The clipping has a mis-match between screen and world space. So `min_x` et al. are in *world* coordinates, and `screen_x` & `screen_y` are in *screen* space. So now I look at it, my code is really broken. Oops.

So what it *should* do is clip the tile based on it being inside the map panel. So if you hard-code in some screen bounds to the clip-check, it also works: `if screen_x > 1 && screen_x < 79 && screen_y > 1 && screen_y < 49 {`. 

That's obviously problematic since the reader might decide to change the clipping bounds, so the 79 needs to be `(max_x - min_x)-1` and the 49 `(max_y - min_y)-1`. So that makes the code:

```rust
if screen_x > 1 && screen_x < (max_x - min_x)-1 && screen_y > 1 && screen_y < (max_y - min_y)-1 {
                    ctx.set_bg(screen_x, screen_y, RGB::named(rltk::BLUE));
                    available_cells.push(idx);
                }
```

On my system that works pretty well. I'll post a fix shortly. Thanks for the heads-up!

**Comment by Zireael07** [comment]
Yay - I just ported the fix to my project and it indeed works!
