### ISSUE TITLE
Logging with Gamelog is O(N)

### ISSUE THREAD

**Issue by MarkMcCaskey** [thebracket/rustrogueliketutorial#80]
Hello!  Thanks for making this tutorial, I'm working through section 1.8 now and I'm really enjoying it so far -- it's fantastic to be able to see and walk-through someone's thought process in system design in an iterative way like this.

I've noticed a few small things that could be improved when going through the tutorial so far and I'd love to help improve them if you're interested in these kinds of changes.

This issue is about the performance of Gamelog, and while it's unlikely to be a bottleneck, it's very easy to drastically improve the performance here!

Code like `gamelog.entries.insert(0, format!("You drink the {}, healing {} hp.", names.get(drink.potion).unwrap().name,  potion.heal_amount),);` requires moving all elements in the vector back by one on every insert, thus O(N) for insert.

Possible solutions:
- Use a [`VecDeque`](https://doc.rust-lang.org/std/collections/struct.VecDeque.html): VecDeques can insert from both the front and the back and should have constant performance here
- Store log messages backwards: use [`Vec::push`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.push) instead of `insert(0, ...)` and use `iter().rev()` to iterate the vector backwards, this should also have constant insertion performance (edit: it's also possible to encapsulate these details by implementing a `log` method on `Gamelog` and implementing an `Iterator` for `Gamelog`, too if you wanted to make incorrect usage impossible)

----

I'd be happy to make a PR updating this, using `sed` or something to update them.  Though now that I'm looking at the repo in more depth, I don't see CI anywhere, would you be interested in having CI set up to ensure all the examples compile before merging pull requests?  Don't let me drag you down a rabbit hole of things that aren't important to you -- but if you are interested I'd love to help out a bit.

**Comment by Zireael07** [comment]
In my own project, I used vec:push as I wanted the newest message on bottom, not top. Wasn't aware that this has improved performance, too!

**Comment by thebracket** [comment]
The whole logging architecture is really rather terrible; it's one of the first bits I wrote, and I'm about 65 chapters into "I really should fix that". I'm torn between making a chapter out of it, and going back to fix it throughout the tutorial.

Advantages to doing a chapter (even one I insert earlier!):

- I can do it *right*. It really shouldn't be an exposed data structure to which anyone can write at any time, and the dependency on making it a writable game resource kills threading (if you are using the dispatcher rather than explicit `run_systems` - the latter is there because of WASM threading limitations).
- I can provide a nice interface, with a builder setup to let you chain log commands. So `log.yellow().text(name).white().text(" eats the rations")` might be a workable syntax. It'd take a chapter to make that work and explain it.
- I could justify another queue setup like the "effects" system to remove the pain, and possibly include some sort of "add to message" functionality to make combining multiple systems' outputs into a single message possible. (For example, "You hit the goblin with your sword for 4 points of damage, it is dead").

Advantages to just fixing the data structure and possibly adding some wrapper calls to make it easier to use (so you aren't exposing the `insert` or `push` or whatever, there's just an implementation method for `add` that hides it):

- It's much easier
- It helps all the existing code in one fell swoop.

**Comment by MarkMcCaskey** [comment]
@thebracket That's a good point!  Doing it as a chapter to make a fancy logging system could be quite interesting too.  I think it's probably a good idea to update the existing code as well though just because it is a bit simpler in my opinion!  I'll try to make a PR for that now and you can merge it in if you like it!

Another idea for an API that just came to mind is something like:
```
gamelog.new_message().append(Color::Yellow("text-like thing goes here because it's defined recursively")).append("Plain text can also go here")
```

With an implementation roughly looking like:

```Rust
trait Loggable {
   fn get_color_value(&self) -> Option<RawColor>;
   // get_text can take a `&mut Writer` or something instead if we want to be super efficient
   fn get_text(&self) -> String; 
}

#[derive(Debug, Clone, Copy)]
enum RawColor {
   Yellow,
}

struct Color<T: Loggable + Sized + 'static> {
    color: RawColor,
    text: T,
}

impl<T: Loggable + Sized + 'static> Color<T> {
    pub fn yellow(text: T) -> Self {
        Self {
            color: RawColor::Yellow,
            text,
        }
    }
}

impl Loggable for String {
   fn get_color_value(&self) -> Option<RawColor> { None }
   fn get_text(&self) -> String { self.clone() }
}
impl Loggable for &str {
   fn get_color_value(&self) -> Option<RawColor> { None }
   fn get_text(&self) -> String { self.to_string() }
}

impl<T: Loggable> Loggable for Color<T> {
   fn get_color_value(&self) -> Option<RawColor> { Some(self.color) }
   fn get_text(&self) -> String { self.text.get_text() }
}

struct MessageBuilder {
    data: Vec<(Option<RawColor>, String)>,
}

impl MessageBuilder {
    fn append<T: Loggable>(&mut self, text: T) -> &mut Self {
        self.data.push((text.get_color_value(), text.get_text()));
        self
    }
}

struct Logger {
    data: Vec<MessageBuilder>,
}

impl Logger {
    pub fn new() -> Self {
        Self {
            data: vec![],
        }
    }
    pub fn new_message(&mut self) -> &mut MessageBuilder {
        self.data.push(MessageBuilder { data: vec![] });
        self.data.last_mut().unwrap()
    }
    
    pub fn render(&self) -> String {
        let mut out = String::new();
        for message in &self.data {
            for segment in &message.data {
                let mut close_tag = "";
                if let Some(color) = segment.0 {
                    let (start, end) = 
                        match color {
                            RawColor::Yellow => ("<yellow>", "</yellow>"),
                        };
                    out += start;
                    close_tag = end;
                }
                out += &segment.1;
                out += close_tag;
            }
            out += "\n";
        }
        
        out
    }
}
```

here's the Rust playground link if you want to run it, https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9480d2c35e84c44918dff42b1a9f0f08 .

The specifics of this code aren't too important, I hacked it out very quickly -- but the idea could be quite neat.
